[build]
  command = "npm run build"  # Adjust this to your build command
  publish = "dist"           # Adjust this to your build output directory

[functions]
  directory = "functions"  # Adjust this if you have serverless functions

# Additional configuration options can be added based on your requirements


  include = ["data.json"]
