[build]
  command = "npm run build"  # Adjust this to your build command
  publish = "dist"           # Adjust this to your build output directory

[functions]
  directory = "functions"  # Adjust this if you have serverless functions

  [functions.include]
    # Add other configuration options as needed
    files = ["data.json"]
